# Copyright (c) 2023 Mohamed Ayoub Jabane (kilwanitro@gmail.com), silentjma on GitHub
name: Fetch products

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'  

jobs:
  fetch-products:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install requests library
        run: pip install requests
        
      - name: Fetch a random products
        run: python zalando_beauty_scraper.py
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add a new products to README.md'
          branch: ${{ github.ref }}
          commit_options: '--no-verify'
